# Generated by Django 2.2 on 2022-03-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WASapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Course',
        ),
    ]
